
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
CONFIG_MCUX_HAS_PRJSEG_project.use_hw_app=n


CONFIG_FREERTOS_MCPP_AUTO_TERMINATE_FINISHED_THREADS=y
CONFIG_FREERTOS_MCPP_SHIM=y
#CONFIG_configKERNEL_PROVIDED_STATIC_MEMORY=y
# FreeRTOS configuration:
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_3=y
CONFIG_MCUX_PRJSEG_middleware.freertos-kernel.generated_config=y
CONFIG_configUSE_PREEMPTION=y
CONFIG_configUSE_TICKLESS_IDLE=0
CONFIG_configCPU_CLOCK_HZ="(SystemCoreClock)"
CONFIG_configTICK_RATE_HZ=1000
CONFIG_configMAX_PRIORITIES=18
CONFIG_configMINIMAL_STACK_SIZE=90
CONFIG_configMAX_TASK_NAME_LEN=20
CONFIG_configUSE_16_BIT_TICKS=n
CONFIG_configIDLE_SHOULD_YIELD=y
CONFIG_configUSE_TASK_NOTIFICATIONS=y
CONFIG_configUSE_MUTEXES=y
CONFIG_configUSE_RECURSIVE_MUTEXES=y
CONFIG_configUSE_COUNTING_SEMAPHORES=y
CONFIG_configQUEUE_REGISTRY_SIZE=8
CONFIG_configUSE_QUEUE_SETS=n
CONFIG_configUSE_TIME_SLICING=n
CONFIG_configUSE_NEWLIB_REENTRANT=n
CONFIG_configENABLE_BACKWARD_COMPATIBILITY=n
CONFIG_configNUM_THREAD_LOCAL_STORAGE_POINTERS=5
CONFIG_configUSE_APPLICATION_TASK_TAG=n
CONFIG_configINCLUDE_FREERTOS_TASK_C_ADDITIONS_H=y
CONFIG_configSUPPORT_STATIC_ALLOCATION=n
CONFIG_configTOTAL_HEAP_SIZE=0
CONFIG_configAPPLICATION_ALLOCATED_HEAP=n
CONFIG_configUSE_IDLE_HOOK=n
CONFIG_configUSE_TICK_HOOK=n
CONFIG_configCHECK_FOR_STACK_OVERFLOW=n
CONFIG_configUSE_MALLOC_FAILED_HOOK=n
CONFIG_configUSE_DAEMON_TASK_STARTUP_HOOK=n
CONFIG_configGENERATE_RUN_TIME_STATS=n
CONFIG_configUSE_TRACE_FACILITY=y
CONFIG_configUSE_STATS_FORMATTING_FUNCTIONS=y
CONFIG_configUSE_CO_ROUTINES=n
CONFIG_configMAX_CO_ROUTINE_PRIORITIES=2
CONFIG_configUSE_TIMERS=y
CONFIG_configTIMER_TASK_PRIORITY="17"
CONFIG_configTIMER_QUEUE_LENGTH=10
CONFIG_configTIMER_TASK_STACK_DEPTH="(configMINIMAL_STACK_SIZE * 2)"
CONFIG_configASSERT(x)="if((x) == 0) {taskDISABLE_INTERRUPTS(); for (;;);}"
CONFIG_INCLUDE_vTaskPrioritySet=y
CONFIG_INCLUDE_uxTaskPriorityGet=y
CONFIG_INCLUDE_vTaskDelete=y
CONFIG_INCLUDE_vTaskSuspend=y
CONFIG_INCLUDE_vTaskDelayUntil=y
CONFIG_INCLUDE_vTaskDelay=y
CONFIG_INCLUDE_xTaskGetSchedulerState=y
CONFIG_INCLUDE_xTaskGetCurrentTaskHandle=y
CONFIG_INCLUDE_uxTaskGetStackHighWaterMark=n
CONFIG_INCLUDE_xTaskGetIdleTaskHandle=n
CONFIG_INCLUDE_eTaskGetState=n
CONFIG_INCLUDE_xTimerPendFunctionCall=y
CONFIG_INCLUDE_xTaskAbortDelay=n
CONFIG_INCLUDE_xTaskGetHandle=n
CONFIG_INCLUDE_xTaskResumeFromISR=y
