# This is the shared manifest file for west module use, regardless of SDK
manifest:
  self:
    path: c2usb
    west-commands: scripts/west-commands.yml
  defaults:
    remote: IntergatedCircuits

  remotes:
    - name: IntergatedCircuits
      url-base: https://github.com/IntergatedCircuits

  projects:
    - name: hid-rp
      revision: 1cf78a8905c13e3670fe4999523cb04ad01f18ee
      import:
        path-prefix: modules/lib

    - name: etl
      url: https://github.com/ETLCPP/etl
      revision: 20.48.1
      clone-depth: 1
      path: modules/lib/etl
