name: MCUXpresso SDK with ARM GCC

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      BOARDS: "frdmk22f frdmmcxn236"
      PRESET: "release"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: latest
          path-env-var: GNUARMEMB_TOOLCHAIN_PATH

      - name: Set ARM_GCC_DIR environment variable
        run: |
          echo "ARM_GCC_DIR=$(dirname $GNUARMEMB_TOOLCHAIN_PATH)" >> "$GITHUB_ENV"

      - name: West workspace setup
        uses: ./.github/template/west-update
        with:
          manifest: west4mcuxsdk.yml

      - name: Build usb-keyboard example for all boards
        working-directory: mcux/examples/usb-keyboard
        run: |
          for BOARD in $BOARDS; do
            echo "=== Building for $BOARD ==="
            west build -d build_$BOARD -- -DBOARD=$BOARD --preset $PRESET
          done
