name: Zephyr Twister build and tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: .
          manifest-file-name: west4nrfsdk.yml
          toolchains: arm-zephyr-eabi

      - name: Workspace setup
        uses: ./.github/template/west-update
        with:
          manifest: west4nrfsdk.yml

      - name: Generate HID usage tables
        run: |
          cmake -S ../modules/lib/hid-rp -B build/hid-rp-codegen \
            -DHID_RP_TESTS=OFF
          cmake --build build/hid-rp-codegen --target hid-usage-tables

      - name: Run twister build and tests
        working-directory: zephyr
        shell: bash
        run: |
          west twister -T . \
            -p native_sim/native/64 -p qemu_cortex_m3 \
            -p nrf52840dk/nrf52840 -p nrf54lm20dk/nrf54lm20a/cpuapp \
            --inline-logs -v
